// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicsaAPI.DAL.Models;

namespace TicsaAPI.DAL.Migrations
{
    [DbContext(typeof(TicsaContext))]
    [Migration("20210322184632_UpdateClientProducer")]
    partial class UpdateClientProducer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicsaAPI.DAL.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompagnieName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("TicsaAPI.DAL.Models.Commentary", b =>
                {
                    b.Property<DateTime>("CommentaryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.HasIndex("IdClient");

                    b.ToTable("Commentary");
                });

            modelBuilder.Entity("TicsaAPI.DAL.Models.Gamme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("CostHisto")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdProducer")
                        .HasColumnType("int");

                    b.Property<int>("IdType")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("StockHisto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdProducer");

                    b.HasIndex("IdType");

                    b.ToTable("Gamme");
                });

            modelBuilder.Entity("TicsaAPI.DAL.Models.GammeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("GammeType");
                });

            modelBuilder.Entity("TicsaAPI.DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("TicsaAPI.DAL.Models.OrderContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGamme")
                        .HasColumnType("int");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGamme");

                    b.HasIndex("IdOrder");

                    b.ToTable("OrderContent");
                });

            modelBuilder.Entity("TicsaAPI.DAL.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("CompagnieName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Producer");
                });

            modelBuilder.Entity("TicsaAPI.DAL.Models.Commentary", b =>
                {
                    b.HasOne("TicsaAPI.DAL.Models.Client", "IdClientNavigation")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .HasConstraintName("FK__Commentar__IdCli__3A81B327")
                        .IsRequired();
                });

            modelBuilder.Entity("TicsaAPI.DAL.Models.Gamme", b =>
                {
                    b.HasOne("TicsaAPI.DAL.Models.Producer", "IdProducerNavigation")
                        .WithMany("Gamme")
                        .HasForeignKey("IdProducer")
                        .HasConstraintName("FK__Gamme__IdProduce__300424B4")
                        .IsRequired();

                    b.HasOne("TicsaAPI.DAL.Models.GammeType", "IdTypeNavigation")
                        .WithMany("Gamme")
                        .HasForeignKey("IdType")
                        .HasConstraintName("FK__Gamme__IdType__2F10007B")
                        .IsRequired();
                });

            modelBuilder.Entity("TicsaAPI.DAL.Models.Order", b =>
                {
                    b.HasOne("TicsaAPI.DAL.Models.Client", "IdClientNavigation")
                        .WithMany("Order")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("FK__Order__IdClient__34C8D9D1")
                        .IsRequired();
                });

            modelBuilder.Entity("TicsaAPI.DAL.Models.OrderContent", b =>
                {
                    b.HasOne("TicsaAPI.DAL.Models.Gamme", "IdGammeNavigation")
                        .WithMany("OrderContent")
                        .HasForeignKey("IdGamme")
                        .HasConstraintName("FK__OrderCont__IdGam__38996AB5")
                        .IsRequired();

                    b.HasOne("TicsaAPI.DAL.Models.Order", "IdOrderNavigation")
                        .WithMany("OrderContent")
                        .HasForeignKey("IdOrder")
                        .HasConstraintName("FK__OrderCont__IdOrd__37A5467C")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
